all: html

SPHINX_PROJECT_NAME = Long-Reverb SliceKit Application Quickstart Guide
VERSION = 0.1
SOURCE_INCLUDE_DIRS = ../app_slicekit_long_reverb
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
