SPHINX_PROJECT_NAME=xSOFTip Audio Delay-line Library
VERSION=1.0
DOXYGEN_DIRS=../../../sw_audio_effect/module_delay
SOURCE_INCLUDE_DIRS=../../../sw_audio_effects
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
