SPHINX_PROJECT_NAME=xSOFTip Audio Loudness Library
VERSION=1.0
DOXYGEN_DIRS=../../../sw_audio_effects/module_dsp_loudness
SOURCE_INCLUDE_DIRS=../../../sw_audio_effects
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
