all: html

SPHINX_PROJECT_NAME = BiQuad Filter SliceKit Application Quickstart Guide
VERSION = 0.1
SOURCE_INCLUDE_DIRS = ../app_slicekit_biquad
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
