SPHINX_PROJECT_NAME=xSOFTip Audio SDRAM_reverb Library
VERSION=1.0
DOXYGEN_DIRS=../../../sw_audio_effect/module_dsp_long_reverb
SOURCE_INCLUDE_DIRS=../../../sw_audio_effects
XDOC_DIR ?= ../../../xdoc
include $(XDOC_DIR)/Makefile.inc
